### ISSUE TITLE
The r10k tries to install all branches

### ISSUE THREAD

**Issue by oscarkraemer** [CSC-IT-Center-for-Science/ansible-role-puppetmaster#7]
At the moment the r10k installs all branches. This is an issues if the Puppetfile in one of the branches is linked to a codebase that is deleted.

This issue would go away if it did not try to install all branches maybe only a defined set of branches.

**Comment by junousi** [comment]
This is already fixed in tag 2018-03-21.

If this is an issue with AKA it would get fixed by updating the tag in requirements.yml from 2016-05-25 to 2018-03-21
